version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    executor: node/default # use the default executor defined within the orb
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: NPM version
          command: npm --version
      - run:
          name: node version
          command: node --version
      - run:
          name: Run tests
          command: npm run test
  package:
    working_directory: ~/repo
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run package
          command: npm run package
      - run:
          name: Run ls
          command: ls ./dist/
      - run:
          command: |
            mkdir -p /tmp/dist
            cp ./dist/panta_*.deb /tmp/dist
      - store_artifacts:
          path: /tmp/dist

workflows:
  version: 2.1
  build_and_package:
    jobs:
      - build
      - package:
          requires:
            - build
          filters:
            branches:
              only:
                - master
   